default_profile = "default"

[values]
room_id = "95297208"

[profiles.default]
token   = "mysecrettoken"

[profiles.debug]
host    = "local.chatwork.com/sub/dir/"
token   = "deadbeefb001"

[profiles.personal]
token   = "cfd0e99946023868f8c098c"
