
default_profile = "ar"

[profiles]

[profiles.a1]
host    = "local.chatwork.com/sub/dir/"
version = "v2"
auth    = "token"
token   = "deadbeefb001"

[profiles.arai]
auth    = "token"
version = "v2"
token   = "cfd0e99946023868f8c098c"
